In [1]:
import numpy

In [2]:
numpy.__version__

'1.11.3'

In [3]:
import numpy as np

In [4]:
np?

In [5]:
L = list(range(10))

In [6]:
type(L[0])

int

In [7]:
L2 = [str(c) for c in L]

In [8]:
type(L2[0])

str

In [9]:
L3 = [True,"2",0,0.4]

In [10]:
[type(item) for item in L3]

[bool, str, int, float]

In [11]:
import array

In [12]:
A = array.array('i',L) # i for integer

In [13]:
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.array(range(10),dtype='int')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.array(range(10),dtype='float32')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.], dtype=float32)

In [17]:
np.array(range(10),dtype='int32')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [18]:
np.array([range(i,i+4) for i in (range(3))])

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [19]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.ones((3,5),dtype='float')

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [21]:
np.ones((3,5),dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [22]:
np.full((3,5),3.14).dtype

dtype('float64')

In [23]:
np.arange(0,20,2) # 2 being step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.linspace(0,1,5) # evenly spaced five floats

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [25]:
np.random((3,3))

TypeError: 'module' object is not callable

In [26]:
np.random.random((3,3))

array([[ 0.23802331,  0.07703555,  0.18876883],
       [ 0.76714115,  0.22625189,  0.52406574],
       [ 0.19462772,  0.83757214,  0.25275146]])

In [27]:
np.random.normal(0,1,(4,3)) # mean, sd, size

array([[-1.85691691,  0.20071562,  1.18998094],
       [-0.20744416,  0.68844966,  0.13535844],
       [ 0.33452729, -2.20987011, -1.09064301],
       [-0.82915661,  1.12654737,  0.10304252]])

In [28]:
np.random.randint(0,10)

8

In [29]:
np.random.randint(0,19,(3,5))

array([[15,  1,  6,  4,  8],
       [15, 18, 17, 12, 14],
       [ 9,  5,  9,  7,  3]])

In [30]:
np.empty((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [31]:
np.empty(3) # values could be anything - whatever present in memory

array([  1.49166815e-154,   2.32035848e+077,   2.23752437e-314])

In [32]:
np.empty(3,dtype='int')

array([0, 0, 0])

In [33]:
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [34]:
np.arange(0,20,2).reshape(2,3)

ValueError: total size of new array must be unchanged

In [35]:
np.arange(0,20,2).reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [36]:
np.random.seed(0)

In [37]:
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [41]:
print("x3 dime",x3.ndim)
print("x3 shape",x3.shape)
print("x3 size",x3.size)
print("x3 dtype",x3.dtype)
print("x3 itemsize",x3.itemsize)
print("x3 nbytes",x3.nbytes)

x3 dime 3
x3 shape (3, 4, 5)
x3 size 60
x3 dtype int64
x3 itemsize 8
x3 nbytes 480


In [42]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [43]:
x1[0]

5

In [44]:
x1[-1]

9

In [45]:
x1

array([5, 0, 3, 3, 7, 9])

In [46]:
x2[0,2]

2

In [47]:
x2[2,-1] # -1 always the last

7

In [48]:
x1[0] = 1.9

In [49]:
x1 # truncated, fix type

array([1, 0, 3, 3, 7, 9])

In [ ]:
# x[start,stop,step]

In [50]:
x = np.arange(10)

In [51]:
x[:5] # 0-4

array([0, 1, 2, 3, 4])

In [52]:
x[5:] # 6th element onwards

array([5, 6, 7, 8, 9])

In [53]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
x[::2]

array([0, 2, 4, 6, 8])

In [55]:
x[1::2] # odd ones

array([1, 3, 5, 7, 9])

In [56]:
x[::-1] # negative step, roles for start, stop reveresed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [57]:
x[5::-2] # reverse every other from index 5

array([5, 3, 1])

In [58]:
x[5:9:-2]

array([], dtype=int64)

In [59]:
x2[2,3]

7

In [60]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [61]:
x2[2,:3]

array([1, 6, 7])

In [62]:
x2[:3,2]

array([2, 8, 7])

In [63]:
x2[:2,:3]

array([[3, 5, 2],
       [7, 6, 8]])

In [64]:
x2[::-1,::-1] # rows and columns both reversed

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [65]:
print(x2[:,0])

[3 7 1]


In [66]:
print(x2[0,:])

[3 5 2 4]


In [67]:
print(x2[0])

[3 5 2 4]


In [68]:
x2_sub = x2[:2,:2]

In [69]:
x2_sub[0,0] = 99

In [70]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [71]:
x2_sub_copy = x2_sub.copy()

In [72]:
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [73]:
x2_sub_copy[0,1]=100

In [74]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [75]:
x2_sub

array([[99,  5],
       [ 7,  6]])

In [76]:
x2_sub_copy

array([[ 99, 100],
       [  7,   6]])

In [77]:
np.array([1,2,3]).reshape(1,3)

array([[1, 2, 3]])

In [78]:
np.array([1,2,3])

array([1, 2, 3])

In [79]:
x = np.array(range(1,4,1))

In [81]:
x.reshape(1,3)

array([[1, 2, 3]])

In [83]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [85]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [88]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [89]:
x = np.array([1,2,3])

In [90]:
y = np.array([4,5,6])

In [91]:
z = np.array([100])

In [92]:
np.concatenate(x,y,z)

TypeError: function takes at most 2 arguments (3 given)

In [93]:
np.concatenate([x,y,z])

array([  1,   2,   3,   4,   5,   6, 100])

In [94]:
np.concatenate([x2,x2])

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7],
       [99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [95]:
np.vstack([x2,x2])

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7],
       [99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [97]:
np.hstack([x2,x2])

array([[99,  5,  2,  4, 99,  5,  2,  4],
       [ 7,  6,  8,  8,  7,  6,  8,  8],
       [ 1,  6,  7,  7,  1,  6,  7,  7]])

In [100]:
x1,x2,x3 = np.concatenate([x,y,z]).split([3,5])

AttributeError: 'numpy.ndarray' object has no attribute 'split'

In [101]:
x1,x2,x3 = np.split(np.concatenate([x,y,z]),[3,5])

In [102]:
print(x1,x2,x3)

[1 2 3] [4 5] [  6 100]


In [104]:
upper,lower = np.vsplit(np.concatenate([x2,x2]),[2])

ValueError: vsplit only works on arrays of 2 or more dimensions

In [105]:
grid = np.arange(4).reshape(2,2)

In [110]:
upper,middle,bottom = np.vsplit(np.concatenate([grid,grid,grid]),[2,4])

In [114]:
first,second,third = np.hsplit(np.hstack([upper,middle,bottom]),[2,4])

In [115]:
first 

array([[0, 1],
       [2, 3]])

In [116]:
upper

array([[0, 1],
       [2, 3]])

In [117]:
bottom == third

array([[ True,  True],
       [ True,  True]], dtype=bool)

In [118]:
3d = np.arange(range(30)).reshape(2,3,5)

SyntaxError: invalid syntax (<ipython-input-118-271f831aed67>, line 1)

In [121]:
threeD = np.arange(30).reshape(2,3,5) # plain, # row, # col

In [122]:
threeD

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [123]:
firstcol, restcol = np.dsplit(threeD,[1]) # split on col, the third dimension

In [124]:
firstcol

array([[[ 0],
        [ 5],
        [10]],

       [[15],
        [20],
        [25]]])

In [125]:
secondcol

array([[[ 1,  2,  3,  4],
        [ 6,  7,  8,  9],
        [11, 12, 13, 14]],

       [[16, 17, 18, 19],
        [21, 22, 23, 24],
        [26, 27, 28, 29]]])

In [126]:
firstplane = threeD[0]
secondplane = threeD[1]
secondplane

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [127]:
firstplane

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [130]:
firstplane,secondplane = np.split(threeD,[1])

In [131]:
firstplane

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [132]:
secondplane

array([[[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [134]:
1/np.arange(5);

/Users/alok/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


In [136]:
np.arange(5)/np.arange(1,6)

array([ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ])

In [137]:
2**np.arange(9).reshape(3,3)

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [139]:
x = np.arange(4)

In [140]:
x//2 # python 3 defualt is float div

array([0, 0, 1, 1])

In [141]:
-x

array([ 0, -1, -2, -3])

In [142]:
x%2

array([0, 1, 0, 1])

In [143]:
np.add(x,3)

array([3, 4, 5, 6])

In [144]:
abs(-x) == x

array([ True,  True,  True,  True], dtype=bool)

In [145]:
np.absolute(-x)

array([0, 1, 2, 3])

In [147]:
np.abs(np.array([0,1+2j,3+4j,-4+3j])) # j not i

array([ 0.        ,  2.23606798,  5.        ,  5.        ])

In [148]:
theta = np.linspace(0,np.pi,3)

In [149]:
np.sin(theta)

array([  0.00000000e+00,   1.00000000e+00,   1.22464680e-16])

In [150]:
np.arcsin(np.sin(theta))

array([  0.00000000e+00,   1.57079633e+00,   1.22464680e-16])

In [151]:
theta

array([ 0.        ,  1.57079633,  3.14159265])

In [152]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692])

In [153]:
np.exp2(x)

array([ 1.,  2.,  4.,  8.])

In [154]:
np.power(x,2)

array([0, 1, 4, 9])

In [155]:
np.power(3,x)

array([ 1,  3,  9, 27])

In [156]:
np.log2(x)

/Users/alok/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log2
  if __name__ == '__main__':


array([      -inf,  0.       ,  1.       ,  1.5849625])

In [157]:
np.log10(x)

/Users/alok/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log10
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.30103   ,  0.47712125])

In [158]:
x = [0,0.01,0.1,0.001]

In [159]:
x

[0, 0.01, 0.1, 0.001]

In [160]:
np.expm1(x)

array([ 0.        ,  0.01005017,  0.10517092,  0.0010005 ])

In [161]:
np.log1p(x)

array([ 0.        ,  0.00995033,  0.09531018,  0.0009995 ])

In [162]:
np.log(x+!)

SyntaxError: invalid syntax (<ipython-input-162-e8eaca486cb0>, line 1)

In [163]:
np.log(np.array(x)+1)

array([ 0.        ,  0.00995033,  0.09531018,  0.0009995 ])

In [164]:
from scipy import special

In [165]:
x = [1,5,10]

In [166]:
special.gamma(x)

array([  1.00000000e+00,   2.40000000e+01,   3.62880000e+05])

In [184]:
x = np.arange(5)
y = np.empty(5)
y = np.multiply(x,10)
print(y)

[ 0 10 20 30 40]


In [185]:
y = np.empty(10)
y


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [186]:
np.power(2,x,out=y[::2])
y

array([  1.,   0.,   2.,   0.,   4.,   0.,   8.,   0.,  16.,   0.])

In [189]:
y = np.zeros(16)
np.power(2,np.concatenate([x,[1,1,1]]),out=y[1::2])

array([  1.,   2.,   4.,   8.,  16.,   2.,   2.,   2.])

In [190]:
y

array([  0.,   1.,   0.,   2.,   0.,   4.,   0.,   8.,   0.,  16.,   0.,
         2.,   0.,   2.,   0.,   2.])

In [191]:
x = np.arange(1,6)

In [192]:
np.add.reduce(x)

15

In [193]:
np.multiply.reduce(x)

120

In [195]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [196]:
x

array([1, 2, 3, 4, 5])

In [197]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [201]:
M = np.random.random((3,4))

In [202]:
big_array = np.random.random(10000000)

In [203]:
%timeit sum(big_array)
%timeit np.sum(big_array)

1 loop, best of 3: 1.08 s per loop
100 loops, best of 3: 6.14 ms per loop


In [204]:
%timeit min(big_array)

1 loop, best of 3: 845 ms per loop


In [205]:
%timeit np.min(big_array)

100 loops, best of 3: 6.04 ms per loop


In [206]:
big_array.min()

1.1260270338375733e-07

In [207]:
print(big_array.sum(),big_array.max())

5000393.68621 0.999999996529


In [208]:
M.sum()

7.4354534940159871

In [209]:
M.sum(axis=0) # along every column

array([ 1.74191123,  1.42695812,  2.39715515,  1.869429  ])

In [210]:
M.min(axis=1) # axis = dimension of the array that will be collapsed

array([ 0.58185033,  0.33800761,  0.31720174])

In [211]:
np.argmin(M)

9

In [214]:
M.min()

0.31720174206929608

In [215]:
M

array([[ 0.65279032,  0.63505887,  0.99529957,  0.58185033],
       [ 0.41436859,  0.4746975 ,  0.6235101 ,  0.33800761],
       [ 0.67475232,  0.31720174,  0.77834548,  0.94957105]])

In [216]:
M.max()
np.argmax(M)

2

In [218]:
np.any(M) # non-zero => True

True

In [219]:
np.all(M)

True

In [220]:
np.median(x)

3.0